const STORAGE_KEY='daymark-state-v1',AUTH_KEY='daymark-auth-v1',API_BASE=(window.DAYMARK_CONFIG?.API_BASE||'').replace(/\/$/,'');
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`,iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,parseDate=v=>{const[y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)},todayIso=()=>iso(new Date());
const seedTasks=()=>[{id:uid(),title:'晨间拉伸',type:'repeat',repeatMode:'daily',startDate:todayIso(),deadline:'07:30'},{id:uid(),title:'喝水 8 杯',type:'repeat',repeatMode:'daily',startDate:todayIso(),deadline:''},{id:uid(),title:'整理明日计划',type:'repeat',repeatMode:'daily',startDate:todayIso(),deadline:'21:30'},{id:uid(),title:'提交周报',type:'specific',date:todayIso(),deadline:'18:00'},{id:uid(),title:'预约牙医',type:'specific',date:todayIso(),deadline:'20:30'}];
const defaultState=()=>({theme:'morning',selectedDate:todayIso(),month:`${todayIso().slice(0,7)}-01`,tasks:seedTasks(),completions:{},profile:{}}),normalizeTask=t=>t.type==='repeat'?{...t,repeatMode:t.repeatMode||'daily',startDate:t.startDate||todayIso()}:t;
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!s)return defaultState();const migrated={...defaultState(),...s,profile:s.profile||{},tasks:(s.tasks||[]).map(normalizeTask)};if((s.tasks||[]).some(t=>t.type==='repeat'&&!t.startDate))localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));return migrated}catch{return defaultState()}}
let state=loadState(),toastTimer,syncTimer,profileAvatarDraft='';
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));scheduleCloudSave()}
const taskOnDate=(t,d)=>t.type==='specific'?t.date===d:(t.repeatMode||'daily')==='daily'?d>=(t.startDate||todayIso()):(!t.startDate||d>=t.startDate)&&(!t.endDate||d<=t.endDate),tasksFor=d=>state.tasks.filter(t=>taskOnDate(t,d)),done=(id,d)=>Boolean(state.completions[d]?.includes(id)),dateMode=d=>d<todayIso()?'past':d>todayIso()?'future':'today';
function setDone(id,d,v){const s=new Set(state.completions[d]||[]);v?s.add(id):s.delete(id);state.completions[d]=[...s];saveState()}
function completionFor(d){const tasks=tasksFor(d),complete=tasks.filter(t=>done(t.id,d)).length;return{tasks,complete,all:tasks.length>0&&complete===tasks.length}}
const $=s=>document.querySelector(s),calendarHeading=$('#calendar-heading'),calendarGrid=$('#calendar-grid'),selectedHeading=$('#selected-date-heading'),dateContext=$('#date-context'),repeatList=$('#repeat-list'),specificList=$('#specific-list'),emptyState=$('#empty-state'),taskList=$('#task-list'),addBottom=$('#add-task-bottom'),dialog=$('#task-dialog'),form=$('#task-form'),accountDialog=$('#account-dialog'),accountForm=$('#account-form');
const escapeHtml=t=>{const d=document.createElement('div');d.textContent=t;return d.innerHTML},formatDate=d=>new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(parseDate(d));
function render(){document.documentElement.dataset.theme=state.theme;document.querySelectorAll('[data-theme-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.themeChoice===state.theme)));renderAccountButton();renderCalendar();renderTasks()}
function renderCalendar(){const m=parseDate(state.month);calendarHeading.textContent=`${m.getFullYear()}年${m.getMonth()+1}月`;calendarGrid.replaceChildren();const first=new Date(m.getFullYear(),m.getMonth(),1),start=new Date(first);start.setDate(1-first.getDay());for(let i=0;i<42;i++){const date=new Date(start);date.setDate(start.getDate()+i);const ds=iso(date),status=completionFor(ds),b=document.createElement('button');b.className='calendar-day';b.setAttribute('role','gridcell');if(date.getMonth()!==m.getMonth())b.classList.add('outside');if(ds===state.selectedDate)b.classList.add('selected');if(ds===todayIso())b.classList.add('today');b.setAttribute('aria-label',`${formatDate(ds)}${status.all?'，全部完成':status.tasks.length?'，有未完成任务':'，没有任务'}`);b.innerHTML=`<span class="day-number">${date.getDate()}</span>${status.all?'<span class="day-status" aria-hidden="true">⌣</span>':'<span class="day-status" aria-hidden="true"></span>'}`;b.onclick=()=>{state.selectedDate=ds;state.month=`${ds.slice(0,7)}-01`;saveState();render();showMobileView('today')};calendarGrid.append(b)}}
function renderTasks(){const mode=dateMode(state.selectedDate),selected=parseDate(state.selectedDate);selectedHeading.textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric'}).format(selected);dateContext.textContent=mode==='today'?'今天':new Intl.DateTimeFormat('zh-CN',{weekday:'long'}).format(selected);const policy=$('#date-policy');policy.hidden=mode==='today';policy.textContent=mode==='past'?'历史记录仅供查看，任务和完成状态不可修改。':'可提前安排任务，完成状态将在当天开放。';const{tasks,complete,all}=completionFor(state.selectedDate),repeat=tasks.filter(t=>t.type==='repeat'),specific=tasks.filter(t=>t.type==='specific');renderGroup(repeatList,repeat,mode);renderGroup(specificList,specific,mode);$('#repeat-count').textContent=repeat.length?`${repeat.filter(t=>done(t.id,state.selectedDate)).length}/${repeat.length}`:'';$('#specific-count').textContent=specific.length?`${specific.filter(t=>done(t.id,state.selectedDate)).length}/${specific.length}`:'';$('#progress-count').textContent=`${complete} / ${tasks.length}`;const p=tasks.length?Math.round(complete/tasks.length*100):0;$('#progress-bar').style.transform=`scaleX(${p/100})`;$('.progress-track').setAttribute('aria-valuenow',String(p));$('#complete-message').hidden=!all;emptyState.hidden=tasks.length>0||mode==='past';taskList.hidden=tasks.length===0;addBottom.hidden=tasks.length===0||mode==='past';['#add-task-top','#empty-add'].forEach(s=>{$(s).hidden=mode==='past';$(s).disabled=mode==='past'})}
function renderGroup(container,tasks,mode){container.replaceChildren();for(const t of tasks){const isDone=done(t.id,state.selectedDate),overdue=!isDone&&t.deadline&&mode!=='future'&&(mode==='past'||t.deadline<new Date().toTimeString().slice(0,5)),completionLocked=mode!=='today',editLocked=mode==='past',repeatLabel=t.type==='repeat'?((t.repeatMode||'daily')==='interval'?`${t.startDate} 至 ${t.endDate}`:'每天'):'';const row=document.createElement('article');row.className=`task-row${isDone?' completed':''}${overdue?' overdue':''}${editLocked?' read-only':''}`;row.innerHTML=`<button class="check-button" ${completionLocked?'disabled':''} aria-pressed="${isDone}" aria-label="${completionLocked?'当前日期不可修改完成状态':isDone?'标记为未完成':'标记为完成'}：${escapeHtml(t.title)}"><span class="check-visual" aria-hidden="true">✓</span></button><div class="task-copy"><div class="task-title">${escapeHtml(t.title)}</div><div class="task-meta">${repeatLabel?`<span>${escapeHtml(repeatLabel)}</span>`:''}${isDone?'<span>已完成</span>':overdue?'<span>已逾期</span>':''}</div></div><time class="deadline">${t.deadline||''}</time>${editLocked?'<span class="locked-mark">只读</span>':`<button class="icon-button edit-button" aria-label="编辑任务：${escapeHtml(t.title)}">⋯</button>`}`;if(!completionLocked)row.querySelector('.check-button').onclick=()=>{setDone(t.id,state.selectedDate,!isDone);render();showToast(!isDone?'任务已完成':'已恢复为未完成')};if(!editLocked)row.querySelector('.edit-button').onclick=()=>openTaskDialog(t);container.append(row)}}
function openTaskDialog(t=null){if(dateMode(state.selectedDate)==='past')return;form.reset();$('#task-dialog-title').textContent=t?'编辑任务':'添加任务';$('#task-id').value=t?.id||'';$('#task-title').value=t?.title||'';$('#task-deadline').value=t?.deadline||'';form.elements['task-type'].value=t?.type||'repeat';form.elements['repeat-mode'].value=t?.repeatMode||'daily';$('#task-date').value=t?.date||state.selectedDate;$('#repeat-start').value=t?.startDate||state.selectedDate;$('#repeat-end').value=t?.endDate||state.selectedDate;['#task-date','#repeat-start','#repeat-end'].forEach(s=>$(s).min=todayIso());$('#delete-task').hidden=!t;$('#task-error').hidden=true;toggleTaskFields();dialog.showModal();setTimeout(()=>$('#task-title').focus(),0)}
function toggleTaskFields(){const repeat=form.elements['task-type'].value==='repeat';$('#repeat-rule-field').hidden=!repeat;$('#repeat-range').hidden=!repeat||form.elements['repeat-mode'].value!=='interval';$('#date-field').hidden=repeat}
form.onchange=e=>{if(['task-type','repeat-mode'].includes(e.target.name))toggleTaskFields()};
function showFormError(m){$('#task-error').textContent=m;$('#task-error').hidden=false}
form.onsubmit=e=>{e.preventDefault();const title=$('#task-title').value.trim(),type=form.elements['task-type'].value,repeatMode=form.elements['repeat-mode'].value,date=$('#task-date').value,startDate=$('#repeat-start').value,endDate=$('#repeat-end').value;if(!title)return showFormError('请输入任务名称');if(type==='specific'&&!date)return showFormError('请选择任务执行日期');if(type==='specific'&&date<todayIso())return showFormError('不能把任务安排到过去的日期');if(type==='repeat'&&repeatMode==='interval'&&(!startDate||!endDate))return showFormError('请选择重复区间');if(type==='repeat'&&repeatMode==='interval'&&startDate>endDate)return showFormError('结束日期不能早于开始日期');const id=$('#task-id').value,existing=id?state.tasks.find(x=>x.id===id):null,t={id:id||uid(),title,type,deadline:$('#task-deadline').value,...(type==='specific'?{date}:repeatMode==='interval'?{repeatMode,startDate,endDate}:{repeatMode:'daily',startDate:existing?.startDate||state.selectedDate})};if(id)state.tasks[state.tasks.findIndex(x=>x.id===id)]=t;else state.tasks.push(t);saveState();dialog.close();render();showToast(id?'任务已保存':'任务已添加')};
['#close-task-dialog','#cancel-task-dialog'].forEach(s=>$(s).onclick=()=>dialog.close());$('#delete-task').onclick=()=>{const id=$('#task-id').value;if(!id)return;state.tasks=state.tasks.filter(t=>t.id!==id);Object.keys(state.completions).forEach(d=>state.completions[d]=state.completions[d].filter(x=>x!==id));saveState();dialog.close();render();showToast('任务已删除')};['#add-task-top','#add-task-bottom','#empty-add'].forEach(s=>$(s).onclick=()=>openTaskDialog());
document.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.themeChoice;saveState();render();showToast(`已切换到${b.textContent.trim()}主题`)});$('#prev-month').onclick=()=>shiftMonth(-1);$('#next-month').onclick=()=>shiftMonth(1);function shiftMonth(n){const d=parseDate(state.month);d.setMonth(d.getMonth()+n);state.month=iso(new Date(d.getFullYear(),d.getMonth(),1));saveState();renderCalendar()}$('#today-button').onclick=()=>{state.selectedDate=todayIso();state.month=`${todayIso().slice(0,7)}-01`;saveState();render()};document.querySelectorAll('[data-mobile-view]').forEach(b=>b.onclick=()=>showMobileView(b.dataset.mobileView));function showMobileView(v){if(matchMedia('(min-width: 50rem)').matches)return;$('#today-view').style.display=v==='today'?'block':'none';$('#calendar-view').style.display=v==='calendar'?'block':'none';document.querySelectorAll('[data-mobile-view]').forEach(b=>b.toggleAttribute('aria-current',b.dataset.mobileView===v));window.scrollTo({top:0,behavior:'smooth'})}
function auth(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
function oauthAvatar(){const a=auth()?.user||{};return a.avatar||a.avatar_url||''}
function identity(){const a=auth()?.user||{};return{name:state.profile?.nickname||a.login||a.name||a.email||'我的账户',account:a.email||a.login||'',avatar:state.profile?.avatar||oauthAvatar(),provider:a.provider==='google'?'Google 账户':'GitHub 账户'}}
function setAvatarPreview(url){const image=$('#profile-avatar'),fallback=$('#profile-avatar-fallback');image.hidden=!url;fallback.hidden=Boolean(url);if(url)image.src=url}
function renderAccountButton(){const button=$('#account-button'),i=identity();button.replaceChildren();if(auth()?.token&&i.avatar){const image=document.createElement('img');image.src=i.avatar;image.alt='';image.referrerPolicy='no-referrer';button.append(image)}else{const span=document.createElement('span');span.setAttribute('aria-hidden','true');span.textContent=auth()?.token?i.name.slice(0,1).toUpperCase():'我';button.append(span)}}
function renderAvatarPicker(){const grid=$('#avatar-grid'),current=profileAvatarDraft||oauthAvatar();grid.replaceChildren();const choices=[...(oauthAvatar()?[{url:'',label:'使用登录账户头像',source:oauthAvatar()}]:[]),...Array.from({length:10},(_,i)=>{const url=`icons/avatars/avatar-${String(i+1).padStart(2,'0')}.webp`;return{url,label:`卡通头像 ${i+1}`,source:url}})];for(const choice of choices){const b=document.createElement('button');b.type='button';b.className='avatar-choice';b.setAttribute('aria-label',choice.label);b.setAttribute('aria-pressed',String((choice.url||oauthAvatar())===current));b.innerHTML=`<img src="${choice.source}" alt="">`;b.onclick=()=>{profileAvatarDraft=choice.url;setAvatarPreview(choice.url||oauthAvatar());grid.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))};grid.append(b)}}
function renderAccountDialog(){const logged=Boolean(auth()?.token);$('#login-view').hidden=logged;$('#profile-view').hidden=!logged;$('#account-title').textContent=logged?'个人资料':'登录日程';if(!logged)return;const i=identity();profileAvatarDraft=state.profile?.avatar||'';$('#profile-display-name').textContent=i.name;$('#profile-provider').textContent=i.provider;$('#profile-nickname').value=state.profile?.nickname||i.name;document.querySelectorAll('[name="profile-gender"]').forEach(r=>r.checked=r.value===state.profile?.gender);$('#profile-account').value=i.account;setAvatarPreview(i.avatar);$('#profile-avatar-fallback').textContent=i.name.slice(0,1).toUpperCase();$('#avatar-field').hidden=true;$('#profile-avatar-button').setAttribute('aria-expanded','false');renderAvatarPicker()}
async function compressAvatar(file){if(!file.type.startsWith('image/'))throw new Error('请选择图片文件');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),size=256;canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d'),scale=Math.max(size/bitmap.width,size/bitmap.height),w=bitmap.width*scale,h=bitmap.height*scale;ctx.drawImage(bitmap,(size-w)/2,(size-h)/2,w,h);bitmap.close?.();return canvas.toDataURL('image/webp',.76)}
$('#avatar-upload').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{profileAvatarDraft=await compressAvatar(file);setAvatarPreview(profileAvatarDraft);$('#avatar-grid').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed','false'));$('#avatar-size-note').textContent=`已压缩至 ${Math.round(profileAvatarDraft.length*.75/1024)} KB`}catch(error){showToast(error.message||'图片无法读取，请换一张图片')}e.target.value=''};
function toggleAvatarLibrary(){const field=$('#avatar-field'),opening=field.hidden;field.hidden=!opening;$('#profile-avatar-button').setAttribute('aria-expanded',String(opening));if(opening)setTimeout(()=>field.scrollIntoView({block:'nearest',behavior:'smooth'}),0)}
$('#profile-avatar-button').onclick=toggleAvatarLibrary;$('#change-avatar-button').onclick=toggleAvatarLibrary;
$('#account-button').onclick=()=>{renderAccountDialog();accountDialog.showModal()};['#close-account-dialog','#cancel-account-login','#cancel-profile'].forEach(s=>$(s).onclick=()=>accountDialog.close());accountForm.onsubmit=e=>{e.preventDefault();if(!auth()?.token)return;const gender=document.querySelector('[name="profile-gender"]:checked')?.value||'';state.profile={nickname:$('#profile-nickname').value.trim()||identity().name,gender,avatar:profileAvatarDraft};saveState();render();accountDialog.close();showToast('个人资料已保存并同步')};$('#logout-button').onclick=()=>{localStorage.removeItem(AUTH_KEY);accountDialog.close();render();showToast('已退出登录，本机任务仍保留')};
async function startOAuth(p){if(!API_BASE){$('#sync-note').textContent='云端 API 尚未配置，请先完成函数计算部署。';return}try{const r=await api(`/auth/${p}/start`);sessionStorage.setItem('daymark-oauth-provider',p);location.assign(r.authorizationUrl)}catch(e){$('#sync-note').textContent=e.message}}$('#github-login').onclick=()=>startOAuth('github');$('#google-login').onclick=()=>startOAuth('google');
function showToast(m){const t=$('#toast');t.textContent=m;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),2200)}async function api(path,{method='GET',body}={}){const token=auth()?.token,r=await fetch(`${API_BASE}${path}`,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})}),data=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401)localStorage.removeItem(AUTH_KEY);throw new Error(data.error||'云端连接失败，请稍后重试')}return data}const cloudAdapter={async list(){return(await api('/api/state')).state},async save(data){return api('/api/state',{method:'PUT',body:{state:data}})}};function scheduleCloudSave(){if(!API_BASE||!auth()?.token)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>cloudAdapter.save(state).catch(()=>showToast('已保存在本机，云端同步稍后重试')),700)}
async function consumeOAuthCallback(){const p=new URLSearchParams(location.search);if(p.has('error')){showToast('登录未完成，请重试');history.replaceState(null,'',location.pathname);return}if(!p.has('code')||!p.has('state'))return;const provider=sessionStorage.getItem('daymark-oauth-provider');if(!['github','google'].includes(provider)){showToast('登录会话已失效，请重新登录');return}try{const r=await api(`/auth/${provider}/exchange`,{method:'POST',body:{code:p.get('code'),state:p.get('state')}});localStorage.setItem(AUTH_KEY,JSON.stringify(r));sessionStorage.removeItem('daymark-oauth-provider');showToast(`${provider==='google'?'Google':'GitHub'} 登录成功`)}catch(e){showToast(e.message)}history.replaceState(null,'',location.pathname)}async function hydrateFromCloud(){if(!API_BASE||!auth()?.token)return;try{const remote=await cloudAdapter.list();if(remote){const needsMigration=(remote.tasks||[]).some(t=>t.type==='repeat'&&!t.startDate);state={...defaultState(),...remote,profile:remote.profile||{},tasks:(remote.tasks||[]).map(normalizeTask)};localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render();if(needsMigration)await cloudAdapter.save(state)}else await cloudAdapter.save(state)}catch(e){showToast(e.message)}}window.daymarkCloudAdapter=cloudAdapter;if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));async function boot(){await consumeOAuthCallback();render();showMobileView('today');await hydrateFromCloud()}boot();
